config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :books
  scope '/rentals' do
    get '/', to: 'rentals#index', as: 'rentals'
    post '/create/:id', to: 'rentals#create', as: 'rental_create'
    post '/finish/:id', to: 'rentals#finish', as: 'rental_finish'
  end
  resources :users
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_in', to: 'static_pages#home', as: 'new_user_session'
    get 'sign_out', to: 'devise/sessions#destroy', as: 'destroy_user_session'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :rentals
  has_many :users, through: :rentals
  validates :title, :author, presence: true

  def rented?
    return rentals.where(finish_date: nil).any?
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :book
  before_create :set_start_and_due_date

  def finished?
    !finish_date.nil?
  end

  private

    def set_start_and_due_date
      self.start_date = Date.today
      self.due_date = 14.days.from_now
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :rentals
  has_many :users, through: :rentals
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    user = User.find_by(uid: access_token['uid'],
                        provider: access_token['provider'])

    unless user
      user = User.create!(name: access_token.info['name'],
                          uid: access_token['uid'],
                          provider: access_token['provider'])
    end

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    books_path
  end

  # This method is a must when using Devise ONLY with Omniauthable
  def new_session_path(scope)
    new_user_session_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @rentals = @book.rentals
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :isbn)
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

    # GET /rentals
    def index
      @rentals = Rental.all
    end

    # GET /rentals/create/:id
    # :id of the book
    def create
      @book = Book.find(params[:id])
      authorize @book, :rent?
      @rental = Rental.create(book: @book, user: current_user)

      if @rental.save
        redirect_to books_url, notice: 'Book was successfully rented.'
      else
        redirect_to books_url, notice: 'Could not rent a book'
      end
    end

    # GET /rentals/finish/:id
    # :id of the rental
    def finish
      @rental = Rental.find(params['id'])
      authorize @rental, :finish?
      @rental.finish_date = Date.today
      if @rental.save
        redirect_to books_url, notice: 'Book was successfully returned'
      else
        redirect_to books_url, notice: 'Book could not be returned'
      end
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success',
                              kind: 'Google'
      sign_in_and_redirect @user
    else
      redirect_to home_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @rentals = @user.rentals
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def book_cover_image(book)
    image_tag(
      "http://images.amazon.com/images/P/#{book.isbn.gsub(/[^0-9,.]/, '')}.01.ZTZZZZZZ.jpg",
      alt: "#{book.title} cover"
    )
  end

  def book_action_button(book)
    if book.rented?
      policy(book.rentals.last).finish? ? button_to('Return', rental_finish_path(book.rentals.last)) : "Rented until #{book.rentals.last.due_date}"
    else
      policy(book).rent? ? (button_to 'Rent', rental_create_path(book)) : 'Cannot rent'
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :title, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_area :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :author, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_area :author, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :isbn, "ISBN", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_area :isbn, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/books/edit.html.erb
<div class="container">
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<br/>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9">
      <h2>Books</h2>
    </div>
    <div class="col-sm-3">
      <p>
        <%= link_to 'Add a new book to the library', new_book_path %>
      </p>
    </div>
  </div>
</div>


<div class="container">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Cover</th>
      <th>Title</th>
      <th>Author</th>
      <th>ISBN</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book_cover_image book %></td>
        <td><%= link_to book.title, book %></td>
        <td><%= book.author %></td>
        <td><%= book.isbn %></td>
        <td>
          <%= book_action_button(book) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/books/new.html.erb
<div class="container">

<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <h1><%= @book.title %></h2>
    <div class="col-sm-2">
      <%= book_cover_image @book %>
    </div>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>ISBN:</strong>
  <%= @book.isbn %>
</p>
<p>
  Rented <strong><%= @book.rentals.count %></strong> times.
</p>

<p>
  <%= book_action_button(@book) %>
</p>


</div>
<h3>History</h3>
<%= render 'shared/rentals_table' %>



<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Delete from the library', @book, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', books_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>μLibrary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> μLibrary</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to '<span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span> Books</a>'.html_safe, books_path %></li>
        <li><%= link_to '<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Rental history</a>'.html_safe, rentals_path %></li>
      </ul>

      <% if current_user %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '<span class="glyphicon glyphicon-user" aria-hidden="true"></span> '.html_safe+current_user.name, current_user %></li>
        <li><%= link_to '<span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout'.html_safe, destroy_user_session_path %></li>
      </ul>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    </header>

    <div id="flash_messages" class="container">
    <% flash.each do |key, value| %>
    <div class="alert alert-success" role="alert">
      <%= content_tag(:div, value, :class => "flash #{key}") %>
    </div>
    <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/rentals/index.html.erb
<div class="container">
<h1>All books rentals history</h1>
<%= render "shared/rentals_table" %>
</div>

app/views/shared/_rentals_table.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Book</th>
      <th>User</th>
      <th>Start</th>
      <th>Finish</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= link_to rental.book.title, rental.book %></td>
        <td><%= link_to rental.user.name, rental.user %></td>
        <td><%= rental.start_date %></td>
        <td><%= policy(rental).finish?  ?  button_to('Return', rental_finish_path(rental)) : rental.finish_date %></td>
        <td><%= rental.due_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <h1 class="logo"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> μLibrary</h1>
    <p> Welcome to a dead-simple Rails app to manage books, perhaps in a small firm's library. </p>
    <%=  current_user ? link_to('Logout', destroy_user_session_path) : link_to("Sign in with Google", user_google_oauth2_omniauth_authorize_path) %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :name, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_area :name, class: "form-control" %>
    </div>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Users</h1>
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container">

<h1>
  <%= @user.name %>
</h1>
<%= link_to 'Edit details', edit_user_path(@user) if policy(@user).edit? %>
<h2>
  Book rentals history
</h2>

<%= render "shared/rentals_table" %>
</div>